apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubefirst-console
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kubefirst.github.io/charts
    targetRevision: 2.0.6
    chart: console
    helm:
      values: |-
        env:
          ADMIN_EMAIL:
            value: ""
          CLUSTER_NAME:
            value: "kubefirst"
          HOSTED_ZONE_NAME:
            value: ""
          GITHUB_HOST:
            value: "github.com"
          GITHUB_OWNER:
            value: "jairofernandez"
          ARGO_WORKFLOWS_URL:
            value: "https://argo.localdev.me"
          VAULT_URL:
            value: "https://vault.localdev.me"
          ARGO_CD_URL:
            value: "https://argocd.localdev.me"
          ATLANTIS_URL:
            value: "https://atlantis.localdev.me"
          METAPHOR_DEV:
            value: "https://metaphor-frontend-development.localdev.me/api"
          METAPHOR_GO_DEV:
            value: "<METAPHOR_GO_DEV>"
          METAPHOR_FRONT_DEV:
            value: "https://metaphor-frontend-development.localdev.me"
          METAPHOR_STAGING:
            value: "https://metaphor-frontend-staging.localdev.me/api"
          METAPHOR_GO_STAGING:
            value: "<METAPHOR_GO_STAGING>"
          METAPHOR_FRONT_STAGING:
            value: "https://metaphor-frontend-staging.localdev.me"
          METAPHOR_PROD:
            value: "https://metaphor-frontend-production.localdev.me/api"
          METAPHOR_GO_PROD:
            value: "<METAPHOR_GO_PROD>"
          METAPHOR_FRONT_PROD:
            value: "https://metaphor-frontend-production.localdev.me"
          KUBEFIRST_VERSION:
            value: "1.11.0"
          USE_TELEMETRY:
            value: "true"
          MACHINE_ID:
            value: "E8E487C1-06F4-556A-AA4F-C3851857DE4B"
          IS_LOCAL:
            value: "true"
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.middlewares: kubefirst-redirect-to-https@kubernetescrd
          className: ""
          hosts:
            - host: kubefirst.localdev.me
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: kubefirst-tls
              hosts:
                - kubefirst.localdev.me
  destination:
    server: https://kubernetes.default.svc
    namespace: kubefirst
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
