metaphor-frontend:
  image:
    repository: ghcr.io/jairofernandez/metaphor-frontend
  imagePullSecrets:
  - name: docker-config
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: production-redirect-to-https@kubernetescrd
    className: ""
    hosts:
      - host: metaphor-frontend-production.localdev.me
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: metaphor-frontend-production-tls
        hosts:
          - metaphor-frontend-production.localdev.me
  metaphor:
    host: https://metaphor-frontend-production.localdev.me/api
  vaultMountPoint: kubefirst
  vaultSecretPath: production/metaphor
  isLocal: true
